# This directory contains RNA-Seq data from the following publication:
#        Silvester E, Ivens A, Matthews KR (2018) A gene expression comparison of 
#   Trypanosoma brucei and Trypanosoma congolense in the bloodstream of the mammalian 
#   host reveals species-specific adaptations to density-dependent development. PLoS 
#   Negl Trop Dis 12(10): e0006863. https://doi.org/10.1371/journal.pntd.0006863

# Data:
# Download from SRA using the sra-toolkit which can be installed from here:
#   https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit
#
# The list of accessions for the files required were saved to a file list_ids.txt
# and a python script download_from_sra.py loops through each accession and downloads it 
# using a prefetch command and a fastq-dump command.
   
   cd data/Trypanosoma
   mkdir -p raw
   python ../download_from_sra.py
   cd ../..

# QC:
# These have been QC filtered with trim-galore

  mkdir -p analysis/Trypanosoma/qc/
  for accession in $(cat data/Trypanosoma/list_ids.txt)
  do
    trim_galore \
      data/Trypanosoma/raw/$accession*.fastq.gz \
      --paired \
      --output_dir analysis/Trypanosoma/qc/ \
      --basename $accession \
      --fastqc \
      --no_report_file
  done

# References:
# To perform RNA-Seq analysis we need reference sequences and annotations for each strain.
#
# For T. congolense, the genbank reference can be found here:
# https://tritrypdb.org/tritrypdb/app/record/dataset/NCBITAXON_1068625
# and is associated with the following publication:
#	Jackson et al., Antigenic diversity is generated by distinct evolutionary mechanisms in African trypanosome species. 
#           Proc Natl Acad Sci U S A. 2012 Feb 28;109(9):3416-21. doi: 10.1073/pnas.1117313109. Epub 2012 Feb 13. PMID: 22331916; PMCID: PMC3295286.
# We downloaded the following on 29/04/2024:
# https://tritrypdb.org/tritrypdb/app/downloads/Current_Release/TcongolenseIL3000/gff/data/
# https://tritrypdb.org/tritrypdb/app/downloads/Current_Release/TcongolenseIL3000/fasta/data/
#
# For T. brucei, the genbank reference can be found here:
# https://tritrypdb.org/tritrypdb/app/record/dataset/NCBITAXON_185431
# and is associated with the following publication:
#     Berriman et al., The genome of the African trypanosome Trypanosoma brucei. Science. 2005 Jul 15;309(5733):416-22. doi: 10.1126/science.1112642. PMID: 16020726.
# We downloaded the following on 29/04/2024:
# https://tritrypdb.org/tritrypdb/app/downloads/Current_Release/TbruceiTREU927/gff/data/
# https://tritrypdb.org/tritrypdb/app/downloads/Current_Release/TbruceiTREU927/fasta/data/
#
# These have been stored in gzip format but can be unzipped using the following

   gunzip -c data/Trypanosoma/reference/TriTrypDB-67_TbruceiTREU927.gff.gz > data/Trypanosoma/reference/TriTrypDB-67_TbruceiTREU927.gff
   gunzip -c data/Trypanosoma/reference/TriTrypDB-67_TbruceiTREU927_Genome.fasta.gz > data/Trypanosoma/reference/TriTrypDB-67_TbruceiTREU927_Genome.fasta
   gunzip -c data/Trypanosoma/reference/TriTrypDB-67_TcongolenseIL3000.gff.gz > data/Trypanosoma/reference/TriTrypDB-67_TcongolenseIL3000.gff  
   gunzip -c data/Trypanosoma/reference/TriTrypDB-67_TcongolenseIL3000_Genome.fasta.gz > data/Trypanosoma/reference/TriTrypDB-67_TcongolenseIL3000_Genome.fasta

# STAR alignment:
# As per the example notebook, we first use STAR to index the reference sequences and then run on the QC-filtered RNA-Seq FASTA files

  mkdir -p analysis/Trypanosoma/star/ref_brucei
  STAR --runThreadN 4 \
    --runMode genomeGenerate \
    --genomeDir analysis/Trypanosoma/star/ref_brucei \
    --genomeFastaFiles data/Trypanosoma/reference/*brucei*_Genome.fasta \
    --sjdbGTFfile data/Trypanosoma/reference/*brucei*.gff \
    --sjdbOverhang 75 \
    --genomeSAindexNbases 11
  mkdir -p analysis/Trypanosoma/star/ref_congolense
  STAR --runThreadN 4 \
    --runMode genomeGenerate \
    --genomeDir analysis/Trypanosoma/star/ref_congolense \
    --genomeFastaFiles data/Trypanosoma/reference/*congolense*_Genome.fasta \
    --sjdbGTFfile data/Trypanosoma/reference/*congolense*.gff \
    --sjdbOverhang 75 \
    --genomeSAindexNbases 11

  for accession in $(head -n6 data/Trypanosoma/list_ids.txt)
  do
    mkdir -p analysis/Trypanosoma/star/$accession
    STAR \
      --genomeDir analysis/Trypanosoma/star/ref_brucei \
      --runThreadN 4 \
      --readFilesIn <(gunzip -c analysis/Trypanosoma/qc/$accession*.fq.gz) \
      --outFileNamePrefix analysis/Trypanosoma/star/$accession/$accession \
      --outSAMtype BAM SortedByCoordinate \
      --outSAMattributes Standard \
      --quantMode TranscriptomeSAM GeneCounts
  done
  for accession in $(tail -n+7 data/Trypanosoma/list_ids.txt)
  do
    mkdir -p analysis/Trypanosoma/star/$accession
    STAR \
      --genomeDir analysis/Trypanosoma/star/ref_congolense \
      --runThreadN 4 \
      --readFilesIn <(gunzip -c analysis/Trypanosoma/qc/$accession*.fq.gz) \
      --outFileNamePrefix analysis/Trypanosoma/star/$accession/$accession \
      --outSAMtype BAM SortedByCoordinate \
      --outSAMattributes Standard \
      --quantMode TranscriptomeSAM GeneCounts
  done

# MultiQC
# We combined the log files from STAR using multiqc with the following command

multiqc --outdir analysis/Trypanosoma/multiqc analysis/Trypanosoma/star/
